quarkus:
  # datasource configuration
  datasource:
    db-kind: postgresql
    username: "automobilemeyer"
    password: "automobilemeyer"
    jdbc:
      url: "jdbc:postgresql://localhost:5432/supply_demand_db"