quarkus:
  # datasource configuration
  datasource:
    db-kind: postgresql
    username: "automobilemeyer"
    password: "automobilemeyer"
    jdbc:
      url: "jdbc:postgresql://localhost:5432/supply_demand_db"


  liquibase:
    migrate-at-start: true
    change-log: db/changeLog.yml