quarkus:
  # datasource configuration
  datasource:
    db-kind: postgres
    username: "automobilemeyer"
    password: "automobilemeyer"
    jdbc:
      url: "jdbc:sqlserver://localhost:5432;databaseName=supply_demand_db"