version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env
    # configure postgres (you must provide this file in the following form:
        #   POSTGRES_USER=<username>
        #   POSTGRES_PASSWORD=<password>
        #   POSTGRES_DB=<databasename>


#default-port: 5432