version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    environment:
      POSTGRES_USER: "automobilemeyer"
      POSTGRES_PASSWORD: "automobilemeyer"
      POSTGRES_DB: supply_demand_db
    ports:
      - "5432:5432"
    container_name: supply_demand_db